controller:
  # HT-MPC Solver Type, lex vs SQP
  type: "SQP"

  # MPC params
  dt: 0.1
  prediction_horizon: 1.
  HT_MaxIntvl: 1
  ST_MaxIntvl: 1

  beta: 0.5
  alpha: 0.05

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 5.
      P: 100.
    BasePos2:
      Qk: 5.
      P: 100.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.01
      Qvb: 0.01
      Qua: 0.01
      Qub: 0.2


