simulation:
  duration: 16

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/htmpc_vs_htidkc_squarewave_phi_grid"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info
