simulation:
  robot:
    home: [ 0., -0, -0.0, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi ]  # standard
  duration: 10

controller:
    # soft constraints parameters
  xu_soft:
    mu: 0.001
    zeta: 0.005
  collision_soft:
    mu: 0.0001
    zeta: 0.005
  ee_upward_soft:
    mu: 0.001
    zeta: 0.005

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 1.0
      P: 10.
    BasePos2:
      Qk: 1.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.1
      Qvb: 0.3
      Qua: 0.04
      Qub: 0.4
      Qdua: 0.01
      Qdub: 0.1

  robot:
    limits:
      state:
        lower: [ -10, -10, -1pi, -0.1pi, -1pi, -1pi, -1pi, -1pi, -1pi,
                   -1.1, -1.1, -2, -2, -2, -3, -3, -3, -3 ]
        upper: [ 10, 10, 1pi, 1.pi, 1pi, 1pi, 1pi, 1pi, 1pi,
                   1.1, 1.1, 2, 2, 2, 3, 3, 3, 3 ]

planner:
  use_joy: True

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/mmseq_vs_motm_time_async_video_new"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info