planner:
  sot_type: "SoTCycle"
  tasks:
    - name: "Base Pos 1"
      frame_id: "base"
      planner_type: "BaseSingleWaypoint"
      target_pos: [2.0, 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 1"
      frame_id: "base"
      planner_type: "EESimplePlanner"
      target_pos: [2.0, 1., 1.]
      hold_period: 4
      tracking_err_tol: 0.02
    - name: "Base Pos 2"
      frame_id: "base"
      planner_type: "BaseSingleWaypoint"
      target_pos: [4., 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 2"
      frame_id: "base"
      planner_type: "EESimplePlanner"
      target_pos: [4., 1., 1.]
      hold_period: 2.5
      tracking_err_tol: 0.02
    - name: "Base Pos 3"
      frame_id: "base"
      planner_type: "BaseSingleWaypoint"
      target_pos: [6., 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 3"
      frame_id: "base"
      planner_type: "EESimplePlanner"
      target_pos: [6., 1., 1.]
      hold_period: 5.
      tracking_err_tol: 0.02

controller:
  mpc_rate: 10 #hz
  penalize_du: True
  ST_MaxIntvl: 1
  collision_constraints_enabled: False
  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 1.
      P: 10.
    BasePos2:
      Qk: 1.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.005
      Qvb: 0.005
      Qua: 0.01
      Qub: 0.05
      Qdua: 0.
      Qdub: 0.1

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/debug"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info


