simulation:
  timestep: 0.03
  duration: 25.
  gravity: [0, 0, -9.81]

  pybullet_connection: "DIRECT"  # "Direct" or "GUI"

  static_obstacles:
    enabled: False

  dynamic_obstacles:
    enabled: False

  # Define virtual cameras to capture static shots of the scene or as a viewpoint
  # for a video. Examples:
  # 1. camera defined by (absolute) target and camera position;
  # 2. camera defined by a target and camera position *relative* to EE initial
  #    position;
  # 3. camera defined by a target position and distance and orientation of the
  #    camera (roll, pitch, yaw in degrees)
  cameras:
    example1:
      target: [4, 0, 0]
      position: [7, -3, 4]
      resolution:
        width: 1920
        height: 1080
    example2:
      relative_target: [4, 0, 0.0]
      relative_position: [3, -3, 3.]
    example3:
      target: [1.28, 0.045, 0.647]
      distance: 1.8
      roll: 0
      pitch: -29
      yaw: 147.6

  # Define videos to be captured during the simulation
  video:
    save_frames: false
    dir: "/home/tracy/Documents/PhD/videos/DEC"
    timestep: 0.0290
    views:
      -
        camera: example1
        name: view1

planner:
  sot_type: "SoTCycle"
  tasks:
    - name: "Base Pos 1"
      planner_type: "BaseSingleWaypoint"
      target_pos: [2.0, 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      target_pos: [2.0, 1., 1.]
      hold_period: 4
      tracking_err_tol: 0.02
    - name: "Base Pos 2"
      planner_type: "BaseSingleWaypoint"
      target_pos: [4., 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 2"
      planner_type: "EESimplePlanner"
      target_pos: [4., 1., 1.]
      hold_period: 2.5
      tracking_err_tol: 0.02
    - name: "Base Pos 3"
      planner_type: "BaseSingleWaypoint"
      target_pos: [6., 0.]
      tracking_err_tol: 0.3
    - name: "EE Pos 3"
      planner_type: "EESimplePlanner"
      target_pos: [6., 1., 1.]
      hold_period: 5.
      tracking_err_tol: 0.02

#controller:
#  type: "SQP_TOL_SCHEDULE"
#  HT_MaxIntvl: 1
#  ST_MaxIntvl: 1
#  rate: 30 #hz
#  slack: False
#
#  cost_params:
#    EEPos3:
#      Qk: 0.2
#      P: 10.
#    BasePos2:
#      Qk: 0.2
#      P: 10.
#    Effort:
#      Qqa: 0.
#      Qqb: 0.
#      Qva: 0.01
#      Qvb: 0.01
#      Qua: 0.02
#      Qub: 0.1

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/TP-IDKC.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/DEC"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info

