simulation:
  timestep: 0.03
  duration: 12.
  gravity: [0, 0, -9.81]

  pybullet_connection: "DIRECT"  # "Direct" or "GUI"

  static_obstacles:
    enabled: False

  dynamic_obstacles:
    enabled: False

  # Define virtual cameras to capture static shots of the scene or as a viewpoint
  # for a video. Examples:
  # 1. camera defined by (absolute) target and camera position;
  # 2. camera defined by a target and camera position *relative* to EE initial
  #    position;
  # 3. camera defined by a target position and distance and orientation of the
  #    camera (roll, pitch, yaw in degrees)
  cameras:
    example1:
      target: [0, 0, 0]
      position: [0, -0, 4]
      resolution:
        width: 1920
        height: 1080
    example2:
      relative_target: [0, 0, 0.5]
      relative_position: [0.4, -5, 0.6]
    example3:
      target: [0., 0., 0.5]
      distance: 3
      roll: 0
      pitch: -45
      yaw: 0.

  # Define videos to be captured during the simulation
  video:
    save_frames: true
    dir: "/home/tracy/Documents/PhD/videos/DEC"
    timestep: 0.060
    views:
      -
        camera: example3
        name: view1

planner:
  sot_type: "SoTTimed"
  tasks:
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      target_pos: [1.48, 0.17, 0.7]
      hold_period: 3.
      tracking_err_tol: 0.02
    - name: "Base Pos 1"
      planner_type: "BaseSingleWaypoint"
      target_pos: [0.0, 0.]
      tracking_err_tol: 0.02
    - name: "Base Pos 2"
      planner_type: "BaseSingleWaypoint"
      target_pos: [-1., 0.]
      tracking_err_tol: 0.02
    - name: "Base Pos 2"
      planner_type: "BaseSingleWaypoint"
      target_pos: [ -1., -1. ]
      tracking_err_tol: 0.02
    - name: "Base Pos 3"
      planner_type: "BaseSingleWaypoint"
      target_pos: [ 0.5, 0.5]
      tracking_err_tol: 0.02
  task_switching_time: [0.5, 3., 6.]


#controller:
#  type: "SQP_TOL_SCHEDULE"
#  HT_MaxIntvl: 1
#  ST_MaxIntvl: 1
#  rate: 30 #hz
#  slack: False
#
#  cost_params:
#    EEPos3:
#      Qk: 0.2
#      P: 10.
#    BasePos2:
#      Qk: 0.2
#      P: 10.
#    Effort:
#      Qqa: 0.
#      Qqb: 0.
#      Qva: 0.01
#      Qvb: 0.01
#      Qua: 0.02
#      Qub: 0.1

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/TP-IDKC.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/DEC"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info

