planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "Base Pos 2"
      planner_type: "BasePosTrajectoryLine"
      frame_id: "base"
      initial_pos: [-0.0, -0.0]
      target_pos: [1.70604085, -1.27885704]
      cruise_speed: 0.5
      tracking_err_tol: 0.02
      end_stop: True
    - name: "EE Pos 1"
      planner_type: "EESimplePlannerBaseFrame"
      frame_id: "base"
      target_pos: [1.5, -2.0, 0.8]
      hold_period: 0.75
      tracking_err_tol: 0.05

controller:
  type: "STMPCSQP"
  home: "space_async_new"

  cost_params:
    ArmJoint:
      Qk: 0.2
      P: 1