simulation:
  robot:
    home: [ 0., -0, 0.pi, 0.5pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, 0.417pi ]  # standard
  duration: 30

controller:
  # robot parameters
  robot:
    limits:
      state:
        lower: [ -10, -10, -1pi, -0.5pi, -1pi, -1pi, -1pi, -1pi, -1pi,
                   -1.1, -1.1, -2, -2, -2, -3, -3, -3, -3 ]
        upper: [ 10, 10, 1pi, 2.pi, 1pi, 1pi, 1pi, 1pi, 1pi,
                   1.1, 1.1, 2, 2, 2, 3, 3, 3, 3 ]
  self_collision_avoidance_enabled: True
  collision_soft:
    mu: 0.00005
    zeta: 0.003

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/HTMPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/mmseq_vs_motm_space_async_exp_video_top"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info