planner:
  sot_type: SoTStatic
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0
    - 0
    - 0
    tracking_err_tol: 0.02
  - frame_id: base
    name: Base Position
    peak_pos:
    - 0.5278030183583317
    - -1.932353210862291
    period: 16
    planner_type: BasePosTrajectorySqaureWave
    round: 1
    tracking_err_tol: 0.02
    valley_pos:
    - 0
    - 0

simulation:
  duration: 16


include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/lex_constraints"
  log_level: 20 # 0 - not set, 10 - debug, 20 - info