planner:
  sot_type: "SoTStatic"
  tasks:
    - name: "EE Pos 1"
      planner_type: "EESimplePlanner"
      frame_id: "EE"
      target_pos: [0., -1.5, 0.0]
      hold_period: 3.
      tracking_err_tol: 0.02
    - name: "Base Pos 1"
      planner_type: "BasePosTrajectoryLine"
      frame_id: "base"
      initial_pos: [0.0, 0.]
      target_pos: [3.0, 0.]
      cruise_speed: 0.75
      tracking_err_tol: 0.02
  use_joy: True

simulation:
  robot:
    home: [ 0., -0, 0.pi, 0.pi, -0.25pi, 0.5pi, -0.25pi, 0.5pi, -0.261 ]  # standard
    tool_vicon_name: ThingContainer


controller:
  type: "HTMPCSQP"
  home: "default"

    # soft constraints parameters
  xu_soft:
    mu: 0.001
    zeta: 0.005
  collision_soft:
    mu: 0.0001
    zeta: 0.005
  ee_upward_soft:
    mu: 0.001
    zeta: 0.005

  # weights for each cost function
  cost_params:
    EEPos3:
      Qk: 1.0
      P: 10.
    BasePos2:
      Qk: 1.
      P: 10.
    Effort:
      Qqa: 0.
      Qqb: 0.
      Qva: 0.1
      Qvb: 0.3
      Qua: 0.04
      Qub: 0.4
      Qdua: 0.01
      Qdub: 0.1
    ArmJoint:   
      Qk: 0.2
      P: 1

include:
  - package: "mmseq_run"
    path: "config/robot/thing.yaml"
  - package: "mmseq_run"
    path: "config/controller/MPC.yaml"
  - package: "mmseq_run"
    path: "config/sim/simulation.yaml"
  - package: "mmseq_run"
    path: "config/scene/empty.yaml"

logging:
  log_dir: "/home/tracy/Documents/PhD/data/base_trajectory_fun"
  log_level: 4 # 0 - not set, 10 - debug, 20 - info
