planner:
  sot_type: SoTTimed
  task_switching_time:
  - 8
  tasks:
  - frame_id: EE
    hold_period: 3.0
    name: EE Position
    planner_type: EESimplePlanner
    target_pos:
    - 0
    - 0
    - 0
    tracking_err_tol: 0.02
  - frame_id: base
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - -0.4055478827997585
    - 1.0309702978300055
    tracking_err_tol: 0.02
  - frame_id: base
    name: Base Position
    planner_type: BaseSingleWaypoint
    target_pos:
    - 0
    - 0
    tracking_err_tol: 0.02
