controller:
  type: "RAL25"
  sdf_collision_avoidance_enabled: True

  control_modes:
    - key: "NavHTMPC"
      package: "mmseq_run"
      path: "config/controller/NavHTMPCWorld.yaml"
    - key: "ManHTMPC"
      package: "mmseq_run"
      path: "config/controller/ManHTMPC.yaml"