benchmark:
  seed: 0
  controller_type: ["lex", "SQP"]
  test_size: 5

  playground_bound:
      xy: [-3., 3.]
      z: [0.5, 3.]

  robot_reach: 3.0

simulation:
  duration: 5.
  pybullet_connection: "DIRECT"  # "Direct" or "GUI"

include:
    - "$PROJECTMM3D_HOME/experiments/config/robot/thing.yaml"
    - "$PROJECTMM3D_HOME/experiments/config/controller/HTMPC.yaml"
    - "$PROJECTMM3D_HOME/experiments/config/sim/simulation.yaml"

logging:
  log_dir: "$PROJECTMM3D_HOME/data/benchmark_random_waypoints"
